version: "3.9"
services:
  springboot:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    networks:
      - network-tier

  mysqldb:
    image: mysql:5.7
    container_name: sv-project-mysqldb
    env_file:
      - "./.env"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - mysql-data:/var/lib/bauction
    ports:
      - "3306:3306"
    networks:
      - network-tier
    platform: linux/amd64

networks:
  network-tier:
    external: true