version: "3.9"
services:
  springboot:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: sv-project-mysqldb
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: "0000"
      CHARACTER_SET_SERVER: utf8

    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - /Users/Shared/data/mysql-test:/var/lib/mysql

    ports:
      - "3306:3306"
    platform: linux/amd64

volumes:
  mysql-data: