#spring:
#  datasource:
#    driver-class-name: "com.mysql.cj.jdbc.Driver"
#    url: "jdbc:mysql://localhost:3306/test_db?useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true"
#    username: "root"
#    password: "0000"
#
#  redis:
#    host: localhost
#    port: 6379
#
#  jpa:
#    database: "mysql"
#    show-sql: "true"
#    hibernate:
#      ddl-auto: "update"
#    properties:
#      hibernate:
#        format_sql: true
#    generate-ddl: true

spring:
  datasource:
    url: jdbc:h2:mem:test_db;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true